services:
  - type: web
    name: pdf-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run frontend.py
    envVars:
      - key: GEMINI_API
        value: "AIzaSyDVsvB8RKPPIEznj9gQ2S89cWexTPdxFhI"
